CREATE PROCEDURE select_participants_by_routing_number_part
PARTITION ON TABLE T_MESSAGE_PACS002 COLUMN message_id
    AS
      SELECT * FROM T_ROUTING_TABLE as R, T_PARTICIPANT as P WHERE R.ROUTING_NUMBER IN (?, ?) AND P.ID = R.PARTICIPANT_ID;